name: Laravel CI TripTrove

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: triptrove_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, ctype, fileinfo, openssl, pdo, mysql, pgsql, sqlite, gd
        tools: composer:v2

    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-progress
        cp .env.example .env
        php artisan key:generate

    - name: Setup Environment
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=triptrove_test" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env
        echo "APP_ENV=testing" >> .env

    - name: Run Migrations
      run: php artisan migrate:fresh --env=testing --force

    - name: Execute Tests
      run: php artisan test
