name: PHP Native CI TripTrove

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: triptrove_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, mysql, gd
        tools: composer:v2

    - name: Install Dependencies
      run: |
        if [ -f "composer.json" ]; then
          composer install --prefer-dist --no-progress
        fi

    - name: Setup Database
      run: |
        mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS triptrove_test"
        if [ -f "database.sql" ]; then
          mysql -h 127.0.0.1 -u root -proot triptrove_test < database.sql
        fi

    - name: Run Basic Tests
      run: |
        # Tes koneksi database
        php -r "
          try {
            new PDO('mysql:host=127.0.0.1;dbname=triptrove_test', 'root', 'root'); 
            echo '✅ DB Connected successfully';
          } catch (PDOException \$e) {
            echo '❌ DB Connection failed: ' . \$e->getMessage();
            exit(1);
          }
        "
        
        # Jalankan PHPUnit jika ada test case
        if [ -f "phpunit.xml" ] || [ -f "phpunit.xml.dist" ]; then
          vendor/bin/phpunit
        elif [ -f "tests/" ]; then
          vendor/bin/phpunit tests/
        else
          echo "ℹ️ No PHPUnit tests found"
        fi
        
        # Jalankan test file spesifik jika ada
        if [ -f "index.php" ]; then
          echo "Running index.php"
          php index.php
        else
          echo "ℹ️ index.php not found"
        fi
