name: PHP Native CI TripTrove

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, mysql, gd
        tools: composer:v2

    - name: Install Dependencies
      run: |
        if [ -f "composer.json" ]; then
          composer install --prefer-dist --no-progress
        fi

    - name: Setup Database
      run: |
        mysql -h 127.0.0.1 -u $DB_USERNAME -p$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS trip_triptrove"
        if [ -f "database.sql" ]; then
          mysql -h 127.0.0.1 -u $DB_USERNAME -p$DB_PASSWORD trip_triptrove < database.sql
        fi

    - name: Run Basic Tests
      run: |
        # Tes koneksi database
        php -r " 
          try {
            \$pdo = new PDO('mysql:host=127.0.0.1;dbname=trip_triptrove', getenv('DB_USERNAME'), getenv('DB_PASSWORD')); 
            echo '✅ DB Connected successfully';
          } catch (PDOException \$e) {
            echo '❌ DB Connection failed: ' . \$e->getMessage();
            exit(1);
          }
        "
        
        # Jalankan PHPUnit jika ada test case
        if [ -f "phpunit.xml" ] || [ -f "phpunit.xml.dist" ]; then
          vendor/bin/phpunit
        elif [ -f "tests/" ]; then
          vendor/bin/phpunit tests/
        else
          echo "ℹ️ No PHPUnit tests found"
        fi
        
        # Jalankan test file spesifik jika ada
        if [ -f "user_login_test.php" ]; then
          echo "Running user_login_test.php"
          php user_login_test.php
        else
          echo "ℹ️ user_login_test.php not found"
        fi
