name: Deploy PHP Project to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/html"

      - name: Import MySQL Database (only if not exists)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DB_EXISTS=$(mysql -u trip_fisan -pDatabasefisan -e "SHOW DATABASES LIKE 'trip_triptrove';" | grep trip_triptrove || true)
            if [ -z "$DB_EXISTS" ]; then
              echo "Database trip_triptrove belum ada, mengimpor dari .sql..."
              mysql -u trip_fisan -pDatabasefisan -e "CREATE DATABASE trip_triptrove"
              mysql -u trip_fisan -pDatabasefisan trip_triptrove < /var/www/html/db/triptrove.sql
            else
              echo "Database trip_triptrove sudah ada, skip import."
            fi

      - name: Set permissions & restart Apache
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chown -R www-data:www-data /var/www/html
            chmod -R 755 /var/www/html
            systemctl restart apache2 || systemctl restart nginx
